### ISSUE TITLE
[1] Search APIs for artist albums and add them to the DB

### ISSUE THREAD

**Issue by JWLD** [JWLD/soundtracks-dev#2]
- [x] Create dev search route / component / view (#3)
- [x] Search API for an artist and list top n results (#4)
- [ ] Search API for all albums by a particular artist and render as a list (#5)
- [x] Edit album info and select all the albums to be added to the DB (#6)
- [x] Query Spotify API for link to album artwork (#7)
- [x] DB query to add finalised info to DB (#8)
